### ISSUE TITLE
return(foo) vs. return foo

### ISSUE THREAD

**Issue by agnat** [charto/nbind#1]
Although most C/C++ veterans are pretty adamant about _not_ using parenthesis in return statements historically this is just a matter of style and thus personal preference. However, C++14 _will_ add semantics to these parenthesis in [some cases](http://stackoverflow.com/questions/4762662/are-parentheses-around-the-result-significant-in-a-return-statement). 

Just a heads up, though...

**Comment by jjrv** [comment]
It seems to only affect decltype return values? Thanks for the hint. I use the parens due to excessive exposure to Scheme...

**Comment by jjrv** [comment]
That kind of a convoluted case might actually come up in these bindings templates, I'll keep that in mind.
