### ISSUE TITLE
Function return type of size_t doesn't compile

### ISSUE THREAD

**Issue by bsergeev** [charto/nbind#10]
Changing the return type of
  static int strLengthStatic(const char* x)    { return strlen(x); }
in test/PrimitiveMethods.cc to size_t
  static size_t strLengthStatic(const char* x)    { return strlen(x); }

causes the following build error:

include/nbind/v8/ValueObj.h(53): error C2228: left of '.toJS' must have class/struct/union [test/build/nbind.vcxproj] 
  include/nbind/v8/ValueObj.h(53): note: type is 'size_t'                                                                                  
  include/nbind/v8/ValueObj.h(46): note: while compiling class template member function 'nbind::WireType nbind::BindingType<ReturnType>::toWireType(ArgType)'                                                                                                                                           
          with                                                                                                                                                  
          [                                                                                                                                                     
              ReturnType=size_t,                                                                                                                                
              ArgType=size_t                                                                                                                                    
          ]                                                                                                                                                      

Building with VS2015.

**Comment by jjrv** [comment]
This is probably because size_t is a 64-bit integer on your system and JavaScript has no equivalent type. It could convert to double and warn about it. That still gives you 53 bits so in many real-world cases it would never get rounded, but if you're doing crypto and don't notice the warning, it could lead to some kind of disaster. I suppose requiring a `#define NBIND_INT64 double` and showing a clearer compiler error otherwise might be best.

**Comment by bsergeev** [comment]
Good point!
I'll switch to uint32_t and will check that my size_t values never exceed its MAX.

**Comment by jjrv** [comment]
Nowadays `size_t` should be supported, see [64-bit integers](https://github.com/charto/nbind#64-bit-integers).
