### ISSUE TITLE
Using several nbind addons at once

### ISSUE THREAD

**Issue by BotellaA** [charto/nbind#104]
Closing https://github.com/charto/nbind/issues/102 and opening this issue to improve the explanation.

I have several C++ libraries, each one is using nbind, so I have several addons in the end. In one library, I define an object and in another one I use this object as a parameter in a function. 

According the error message, the second library does not recognize the object. This error is thrown from BindClass.h:248. From the comment above the thrown (_Test that a JavaScript object is an instance of a class from this addon and has some data attached_), it seems what I want to do is not currently possible.

Is my interpretation right? If so, is there a way to make it work?
I am mainly a C++ developer but maybe I could help if something has to be done to make it work.

Thanks for your help

**Comment by BotellaA** [comment]
@jjrv do you have an idea on how to solve this? It prevents me from using nbind at the moment and I really want to use this project.

Is there some kind of dynamic dependency that we could do with nbind?

**Comment by jjrv** [comment]
I still need to investigate this. Multiple addons calling each other directly would be very useful to get working, but there's multiple issues to solve:

- How the addons find each others' headers at compile time.
- How dynamic linking works. You probably need to use `dlopen` or `uv_dlopen` to make any calls across addons.
- Getting nbind's internal typing information working. The addons would need to communicate type tags to each other to initialize successfully.

**Comment by parro-it** [comment]
I don't know if it can be related, but I had to add "-fvisibility" flag in `cflags` section
of `libui-node` binding.gyp, in order to allow proton-native to use both `libui-node` and yoga layout together. Otherwise, there are conflicts between exported libraries...
