### ISSUE TITLE
Asm.js fails to build

### ISSUE THREAD

**Issue by okhick** [charto/nbind#109]
I'm trying to build the example. Native binary compiles just fine but trying to compile an Ams.js fails with the following errors: 

/Volumes/MacintoshHD/nodetests/nbindTest/nBindAsm/node_modules/nbind/bin/emcc: line 21: emcc: command not found
make: *** [Release/obj.target/nbind/hello.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Volumes/MacintoshHD/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.2.0
gyp ERR! command "/Volumes/MacintoshHD/.nvm/versions/node/v8.9.4/bin/node" "/Volumes/MacintoshHD/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--asmjs=1"
gyp ERR! cwd /Volumes/MacintoshHD/nodetests/nbindTest/nBindAsm
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ node-gyp: `node-gyp "configure" "build" "--asmjs=1"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ node-gyp script.

Looks like a problem with node-gyp? Not sure if this is a bug or user error but I'm stumped. Any feedback is greatly appreciated!

**Comment by jjrv** [comment]
The `emcc` command is included in the Emscripten compiler, which you'll need to install first. Emscripten is designed to compile C++ code into Asm.js.  It adds the command in your path.

**Comment by okhick** [comment]
Ahh apparently my Emscripten install did not add to the path... Got it working now. Thanks!
