### ISSUE TITLE
Support complex data structures

### ISSUE THREAD

**Issue by jjrv** [charto/nbind#11]
Something like `emscripten::val` could replace `nbind::cbFunction` and besides calling functions could allow also accessing objects and arrays by numeric or string keys.

In some cases it might be useful to pass a JSON object using something like [nlohmann/json](/nlohmann/json) (or [miloyip/nativejson-benchmark](/miloyip/nativejson-benchmark) has a list of other library options) and avoid roundtrips between C++ and JavaScript at every access.

**Comment by bsergeev** [comment]
How about adding support for (some) STL containers like std::pair?
If nbind could define some typical types like std::pair<int,int> as well as provide their JS counterparts and default bindings, this would make passing such containers much easier.
(I am not sure if embind provides similar facilities...)

**Comment by jjrv** [comment]
Embind supports both `std::vector` and `emscripten::val` for passing JavaScript arrays, and `std::vector` support is also planned for nbind very soon. Then `std::map` corresponding to JavaScript objects would be next.

**Comment by jjrv** [comment]
Let's track this in a [project](https://github.com/charto/nbind/projects/4) instead.
