### ISSUE TITLE
Strange compilation error on Windows

### ISSUE THREAD

**Issue by parro-it** [charto/nbind#112]
I'm getting a strange compile error when compiling on Windows using node 4 and 5:

```
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers [C:\projects\libui-node\build\nbind.vcxproj]
81  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNotifyHook2'
```

The build complete successfully with node 6,8 and 9

I tried to use MSVS 2013 and 2017, but seems they are no more supported and not yet supported...
Could the error depend by same conflict with `nbind` internal functions?

The complete build log is on appveyor here: https://ci.appveyor.com/project/parro-it/libui-node/build/1.0.127

**Comment by jjrv** [comment]
VS 2017 should ne supported now, but it seems the issue is an incompatibility between headers shipped with VS and node-gyp.

**Comment by parro-it** [comment]
Thank you for the suggestion, I found sn issue on node-gyp repo, problem solved by installing latest npm version
