### ISSUE TITLE
Function overloading works only specifing an alternate JS name for the function

### ISSUE THREAD

**Issue by parro-it** [charto/nbind#113]
We are trying to declare a class with two overloaded fucntions.
The functions have following signature:

```cpp
void UiAttributedString::appendAttributed(const char *str, UiFontAttribute *attr);
void UiAttributedString::appendAttributed(const char *str, UiFontAttribute *attr, UiFontAttribute *attr2);
```

Overloading works well if we specify an alternate name:

```cpp
multimethod(appendAttributed, args(const char *, UiFontAttribute *));
multimethod(appendAttributed, args(const char *, UiFontAttribute *, UiFontAttribute *), "appendAttributed2");
```

But fails if we remove it, with this error:

```
/Users/parroit/repos/libui-node/examples/text.js:40
str.appendAttributed('underline color',
    ^

Error: Wrong number of arguments, expected 2
    at Object.<anonymous> (/Users/parroit/repos/libui-node/examples/text.js:40:5)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
```

Could be we misunderstand how the feature works...

**Comment by parro-it** [comment]
Could it depend on [this check](https://github.com/parro-it/nbind/blob/master/include/nbind/signature/BaseSignature.h#L180)?
BTW, it seems to come from a PR of mines 😇

**Comment by parro-it** [comment]
It works well if I skip that check, but it seems weird to let it gone...

```cpp
...

               if(false && !arityIsValid(nanArgs)) {
			// TODO: When function is overloaded, this test could be skipped...

			std::string msg = "Wrong number of arguments, expected " + std::to_string(sizeof...(Args));
			Nan::ThrowError(msg.c_str());
			return;
		}

...
```

If you can suggest me a way to check if the function is overloaded, I can write a PR where
the check is skipped only for overloaded functions.

**Comment by mischnic** [comment]
This doesn't seem to fix it:

added in Overload.cc:
```cpp
unsigned int why(unsigned int x) { return(3); }
unsigned int why(unsigned int x, unsigned int y) { return(4); }

multimethod(why, args(unsigned int));
multimethod(why, args(unsigned int, unsigned int));
```
The test fails:
```js
t.strictEqual(obj.why(0), 3);
t.strictEqual(obj.why(0, 0), 4); // RETURNS 3
```

**Comment by jjrv** [comment]
The [overloaded functions](https://github.com/charto/nbind#overloaded-functions) section mentions that the overloads need to be distinctly named in JavaScript, like:

```TypeScript
multimethod(why, args(unsigned int));
multimethod(why, args(unsigned int, unsigned int), "why2");
```

Then a JS wrapper can check arguments and select which native function to call.

**Comment by parro-it** [comment]
It works well that way, but the docs are ambiguous according to me:

```
In bindings, one of the versions needs to be explicitly selected. The second of the two would be referenced like:

multimethod(test, args(unsigned int, unsigned int));

***If*** it needs to be renamed, the call would be:

multimethod(test, args(unsigned int, unsigned int), "test2");

```

(Enphasis on *if* mine)

Anyway, I'm not a native English speaker, so maybe it's just me...

**Comment by jjrv** [comment]
The *reason* for this is, that it binds a JS function to a C++ function, which is one of the overloads. Otherwise, it would need to generate a new C++ function that checks the arguments. This would result in:

- Larger native binary.
- Not faster, possibly slower execution.

**Comment by parro-it** [comment]
> The reason for this is, that it binds a JS function to a C++ function, which is one of the overloads. 

Yes, I understand the implication. I was thinking the feature is already implemented someway. Thank you!

**Comment by jjrv** [comment]
You're right that the docs were very badly written. Hopefully they're clearer now.

**Comment by parro-it** [comment]
Yes, long way clearer, good job, and thank you again!
