### ISSUE TITLE
Callbacks lifetime

### ISSUE THREAD

**Issue by parro-it** [charto/nbind#15]
Hi, I'm planning on using `nbind` to write [libui](https://github.com/andlabs/libui) bindings for node.
`nbind` will greatly simplify the job, but I will need to use callbacks for UI events...

> Warning: currently callbacks have a very short lifetime! They can be called only until the first function that received them returns. That means it's possible to create a function like Array.map which calls a callback zero or more times and then returns, never using the callback again. It's currently not possible to create a function like setTimeout which calls the callback after it has returned.

Will this limitations of callbacks usage be removed in near future? There is some known workaround to make them work (as in `setTimeout` usage)?

**Comment by jjrv** [comment]
I'll look into this ASAP, others have been requesting the same thing. It seems [nan](https://github.com/nodejs/nan) may have lifted some earlier restriction, since I don't see any serious difficulty in implementing this now.

**Comment by jjrv** [comment]
Wow, I'm impressed how your bindings are already using nbind quite extensively. I got them working on my development machine and will be testing with callbacks soon. It seems to me they may already work, the callback reference you receive as a parameter will become invalid after the call returns, but you can do:

`nbind::cbFunction *persistentCallback = new nbind::cbFunction(callback);`

It's never been tested though, so we'll see. Note that the callback must be called in the same thread where V8 runs or it will crash. Fixing that will require using `Nan::AsyncWorker` and is hopefully not yet necessary.

**Comment by parro-it** [comment]
> Wow, I'm impressed how your bindings are already using nbind quite extensively.
You did an awesome job with nbind :+1: 

> will be testing with callbacks soon
I'll create a separate branch with a failing test that uses nbind callbacks. You can use it to test nbind if you want.

>  Note that the callback must be called in the same thread where V8 runs or it will crash.
libui run in the javascript thread by default, so this shouldn't be a problem.

**Comment by parro-it** [comment]
There is a multithread [`libui` example](https://github.com/andlabs/libui/blob/master/examples/cpp-multithread/main.cpp) but I actually not support them to avoid the problem.
But it could be a useful improvement in future...

**Comment by parro-it** [comment]
I successfully implemented WindowOnClosing before switching to nbind on [this commit](https://github.com/parro-it/libui-node/blob/28e1827e0e2ddccb1b089f1c3d8538182cd843fa/libui.cc#L141) in libui-node if it could be useful for some reference...

**Comment by parro-it** [comment]
>  It seems to me they may already work, the callback reference you receive as a parameter will become invalid after the call returns, but you can do:
```c++
nbind::cbFunction *persistentCallback = new nbind::cbFunction(callback);
```
It's never been tested though, so we'll see.

It's working well, after I save the callback as you suggested... you can see [here](https://github.com/parro-it/libui-node/blob/d31fb53ecc1a888d35d59cb271f968e68d45a1a2/src/UiEntry.cc#L36) how I implemented the `change` event for a widget.

Thank you!
