### ISSUE TITLE
long or unsigned long not supported

### ISSUE THREAD

**Issue by parro-it** [charto/nbind#19]
I get an error if I use `long` or `unsigned long` argument:

```
../node_modules/nbind/include/nbind/v8/ValueObj.h: In instantiation of ‘static nbind::WireType nbind::BindingType<ArgType>::toWireType(ArgType) [with ArgType = long int; nbind::WireType = v8::Local<v8::Value>]’:
../node_modules/nbind/include/nbind/v8/Caller.h:76:63:   required from ‘static nbind::WireType nbind::MethodResultConverter<ReturnType>::toWireType(ReturnType&&, Bound&) [with Bound = UiColorButton; ReturnType = long int; nbind::WireType = v8::Local<v8::Value>]’
../node_modules/nbind/include/nbind/v8/Caller.h:94:3:   required from ‘static nbind::WireType nbind::Caller<ReturnType, nbind::TypeList<Args ...> >::callMethod(Bound&, MethodType, NanArgs&) [with Bound = UiColorButton; MethodType = long int (UiColorButton::*)(); NanArgs = const Nan::FunctionCallbackInfo<v8::Value>; ReturnType = long int; Args = {}; nbind::WireType = v8::Local<v8::Value>]’
../node_modules/nbind/include/nbind/signature/MethodSignature.h:34:3:   required from ‘static void nbind::MethodSignature<PtrType, Bound, ReturnType, Args>::callInner(V8Args&, NanArgs&, Bound*) [with V8Args = const Nan::FunctionCallbackInfo<v8::Value>; NanArgs = const Nan::FunctionCallbackInfo<v8::Value>; PtrType = long int (UiColorButton::*)(); Bound = UiColorButton; ReturnType = long int; Args = {}]’
../node_modules/nbind/include/nbind/signature/BaseSignature.h:198:46:   required from ‘static void nbind::TemplatedBaseSignature<Signature, ReturnType, Args>::callInnerSafely(V8Args&, NanArgs&) [with Bound = UiColorButton; V8Args = const Nan::FunctionCallbackInfo<v8::Value>; NanArgs = const Nan::FunctionCallbackInfo<v8::Value>; Signature = nbind::MethodSignature<long int (UiColorButton::*)(), UiColorButton, long int>; ReturnType = long int; Args = {}]’
../node_modules/nbind/include/nbind/signature/MethodSignature.h:38:53:   [ skipping 2 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
../node_modules/nbind/include/nbind/signature/MethodSignature.h:16:7:   required from ‘static Signature& nbind::TemplatedBaseSignature<Signature, ReturnType, Args>::getInstance() [with Signature = nbind::MethodSignature<long int (UiColorButton::*)(), UiColorButton, long int>; ReturnType = long int; Args = {}]’
../node_modules/nbind/include/nbind/BindDefiner.h:77:28:   required from ‘void nbind::BindDefiner<Bound>::addMethod(const char*, MethodType) [with Signature = nbind::MethodSignature<long int (UiColorButton::*)(), UiColorButton, long int>; MethodType = long int (UiColorButton::*)(); Bound = UiColorButton]’
../node_modules/nbind/include/nbind/BindDefiner.h:86:12:   required from ‘void nbind::BindDefiner<Bound>::addMethodMaybeConst(const char*, ReturnType (Bound::*)(Args ...)) [with Signature = nbind::MethodSignature; ReturnType = long int; Args = {}; Bound = UiColorButton]’
../node_modules/nbind/include/nbind/BindDefiner.h:123:22:   required from ‘nbind::BindDefiner<Bound>& nbind::BindDefiner<Bound>::function(const char*, MethodType, Policies ...) [with MethodType = long int (UiColorButton::*)(); Policies = {}; Bound = UiColorButton]’
../src/UiColorButton.cc:45:2:   required from ‘BindInvokerUiColorButton<Bound>::BindInvokerUiColorButton() [with Bound = UiColorButton]’
../src/UiColorButton.cc:41:1:   required from here
../node_modules/nbind/include/nbind/v8/ValueObj.h:59:3: error: request for member ‘toJS’ in ‘arg’, which is of non-class type ‘long int’
   arg.toJS(construct);
```

It appear nbind does not recognized as a basic type it and try to implement it as object, requiring a `toJS` member to convert it.

I get this while implmenting UiColorButton on libui-node [on this branch](https://github.com/parro-it/libui-node/tree/color-button)

**Comment by jjrv** [comment]
You're probably on a 64-bit platform and JavaScript doesn't have 64-bit integers. Problem is then, what should we convert to? Options are:

- Double, potentially losing the lowest 11 bits of precision.
- Integer, potentially losing the highest 32 bits.
- Custon bignum type holding a lower and higher half (would need implementing).

Which one do you think would work in your case? In issue #8 is listed a plan to support the last one of those options.

**Comment by parro-it** [comment]
> Custon bignum type holding a lower and higher half (would need implementing).

I think this could be the better choice, maybe there are some usable library on NPM?

Thinking more of how to implement my use case (Color representation) it could be better to use a custom class to pass by value that hold r,g,b,a values...

**Comment by jjrv** [comment]
Usually rgba values fit in `uint32_t` which would be a cross-platform way to refer to the type. If each color channel is not an integer between 0-255 then maybe an `std::Array<double, 4>` (or substitute `uint16_t` for `double`, whatever is the most appropriate) would be a good choice of type on the C++ side and efficient to transfer between the languages.

**Comment by parro-it** [comment]
`libui` function actually receive color as 4 `double` arguments. The problem is that in the getter it's using always 4 arguments passed by reference. So I thought to compact them in single value.

Later I thought that could be better to use a custom class. `std::Array<double, 4>` would probably be simpler to implement, but I like the ability to refer to individual color components by name instead that 
indexing an array.

**Comment by jjrv** [comment]
In that case please take a look at value types:

https://github.com/charto/nbind#using-objects

Basically you'd have a JavaScript class:

```JavaScript
function RGBA(r, g, b, a) {
  this.r = r;
  this.g = g;
  this.b = b;
  this.a = a;
}

Coord.prototype.fromJS = function(output) {
  output(this.r, this.g, this.b, this.a);
}

binding.bind('RGBA', RGBA);
```

and a C++ class:

```C++
NBIND_CLASS(RGBA) {
  construct<double, double, double, double>();

  getset(getR, setR);
  getset(getG, setG);
  getset(getB, setB);
  getset(getA, setA);
}
```

Then you should be able to pass them around (by value, not reference or pointer) and everything should look nice in both languages.

**Comment by parro-it** [comment]
> In that case please take a look at value types:

Already given! Was thinking to use exactly that. But thank you for your example I will copy-paste it 😄

**Comment by parro-it** [comment]
Color implemented! The by-value stuff works perfectly! Thank you for your help!

**Comment by jjrv** [comment]
The custom 64-bit bignum is now mostly implemented in the v0.3 branch but there's an additional problem... `int64_t` which is `long long` in my GCC now gets converted but I'm not sure what to do about plain `long`... It would normally become a JavaScript number on 32-bit platforms and an object on 64-bit platforms. This will surely create portability issues... I could force it to always be an object but that seems slow and impractical when not actually needed, especially when targeting asm.js.

**Comment by parro-it** [comment]
That's good news @jjrv! One option could be to let the user choose, may with a property in config file?

**Comment by jjrv** [comment]
This should now be done, just missing documentation.
