### ISSUE TITLE
Interface to jxcore

### ISSUE THREAD

**Issue by brodybits** [charto/nbind#2]
Thanks for publishing this project which you announced in nodejs/nan#437! It definitely looks much easier than following nodejs.org/api/addons.html and I can see some advantages over existing NAN API as well. The JXCore project supports multiple JS engines (currently V8 and SpiderMonkey) which is essential for supporting multiple mobile platforms. They made their own JS native interface as documented in https://github.com/jxcore/jxcore/tree/master/doc/native and it looks like a major feat for supporting multiple JS engines. It would be great if this project would support JXCore as well.

I am planning look into this in the next week or so, will keep you posted. I am raising this issue in case any others will have input.

**Comment by jjrv** [comment]
I was just looking into what it would take to support Cordova, but it would seem to require Java or Objective C glue code between the C++ and JavaScript. From a quick look at their roadmap it seems JXcore is doing something on that front, thank you very much for mentioning them. I'd be very interested in any way to support native code on mobile in addition to the existing Node.js and upcoming Emscripten, by just plugging another interface to nbind.

I've already got a nice technology stack of nbind, Polymer, SystemJS and TypeScript working on Electron and would like to take that to both browser and mobile. Emscripten will handle all platforms but native would be much better on mobile, as I guess asm.js is not there yet.

I'll try to find time to post about nbind implementation details on [my blog](http://blog.charto.net/) but right now I'm very busy working on the Emscripten support. I just finished a pretty major refactoring and now the code is starting to look reasonable for supporting other environments besides Node.js.

**Comment by jjrv** [comment]
I've added some documentation about the internals at https://github.com/charto/nbind/blob/feature/emscripten-support/INTERNALS.md if you want to look at nbind's source code.

**Comment by jjrv** [comment]
So it seems for example on iOS JXcore runs its own SpiderMonkey and can talk to Cordova, which runs JavaScriptCore and can handle showing things on the screen. For connecting C++ to the UI, JXcore seems to be a rather heavy bridge.

I was also thinking of using React Native instead. It also runs JavaScriptCore and has a web view, but the UI elements should be much nicer and more performant than anything doable in HTML. This would seem to require some Objective C or Java glue code, but probably not that much.

First the JavaScript and C++ have to know that both are initialized, and then the C++ side can send class information (ID numbers, names and ID numbers of method argument types) to JavaScript through the bridge. JavaScript can generate wrappers dynamically and the rest of the communication is just about exchanging numbers and strings. Once the Android version of React Native comes out, things should work similarly over a Java bridge.

Is there a particular reason to using JXcore? At least the [jxcore-cordova](https://github.com/jxcore/jxcore-cordova) code would be a good reference how to write a bridge between C++ (as used in JXcore) and Objective C or Java (as used in Cordova).

**Comment by brodybits** [comment]
You are absolutely right that JXCore uses its own SpiderMonkey (for iOS), and I do not think it is such a good thing either. For iOS mobile apps, React Native would be much nicer. Also did you see Native Script by Telerik, which seems to provide more general-purpose binding and already supports Android (with Windows Mobile coming in the future)?

To be honest, I will probably not use nbind in the near future. The Node.js addon and NAN can also support a factory for a new object with native function member(s), which I did not find in this project unless I am mistaken. Also this project seems to marshall all object members between Javascript and native code, which is not necessary for NAN. It would be a really nice enhancement to get this working someday in the future.

**Comment by jjrv** [comment]
Object members are marshalled when passed by value. Otherwise if you return a stack-allocated object to JavaScript, there's no place for it to go (other than the heap). There's still features missing, it at least will support constructing objects through and passing objects using pointers, which causes any access from JavaScript to call C++ functions (not sure how that works now, as it's not in any tests).

Marshalling is a convenience for asm.js, since its garbage collector doesn't call any destructors. In nbind, C++ preferably receives and returns stack-allocated objects, and they're automatically destroyed and converted into JavaScript objects, which do get garbage collected. This prevents memory leaks. Also, if the object will be frequently accessed from JavaScript, it's faster to not call getters and setters from C++. This is really meant for small objects like a coordinate pair, not big ones like a tree structure.
