### ISSUE TITLE
Maybe feature request : implement "pass by proxy" classes

### ISSUE THREAD

**Issue by parro-it** [charto/nbind#20]
I started implementation of `libui` uiArea APIs.
An uiArea expected an uiAreaHandler struct holding pointers to functions that will handle drawing on the area itself:

```c
struct uiAreaHandler {
	void (*Draw)(uiAreaHandler *, uiArea *, uiAreaDrawParams *);
	void (*MouseEvent)(uiAreaHandler *, uiArea *, uiAreaMouseEvent *);
	void (*MouseCrossed)(uiAreaHandler *, uiArea *, int left);
	void (*DragBroken)(uiAreaHandler *, uiArea *);
	int (*KeyEvent)(uiAreaHandler *, uiArea *, uiAreaKeyEvent *);
};
```

The uiArea widget invoke these functions when it need to redraw the area.
I cannot use class by reference here, because they need to be implemented in js by caller. And neither class by value, because functions will be executed on the native side with them...

So I and up building a struct that hold the needed pointers, and a subsequent set of nbind::cbFunction, one for each function pointer.

```c++

typedef struct UiAreaHandler {
	void (*Draw)(UiAreaHandler *self, UiArea *area, UiAreaDrawParams *params);
	void (*MouseEvent)(UiAreaHandler *self, UiArea *area, UiAreaMouseEvent *event);
	void (*MouseCrossed)(UiAreaHandler *self, UiArea *area, int left);
	void (*DragBroken)(UiAreaHandler *self, UiArea *area);
	int (*KeyEvent)(UiAreaHandler *self, UiArea *area, UiAreaKeyEvent *event);

	nbind::cbFunction *draw;
	nbind::cbFunction *mouseEvent;
	nbind::cbFunction *mouseCrossed;
	nbind::cbFunction *dragBroken;
	nbind::cbFunction *keyEvent;
} UiAreaHandler;

```

Then, I created a set of functions that call the js callbacks, and set their addresses on the struct, e.g.:

```c
void Draw (UiAreaHandler *self, UiArea *area, UiAreaDrawParams *params) {
	(*(self->draw))();
}
```

And a factory function that is called from javascript with a set of js functions as arguments:

```cpp
UiAreaHandler * UiAreaHandlerFactory::build(
	nbind::cbFunction &drawCb,
	nbind::cbFunction &mouseEventCb ,
	nbind::cbFunction &mouseCrossedCb,
	nbind::cbFunction &dragBrokenCb,
	nbind::cbFunction &keyEventCb
) {
	UiAreaHandler *handler = new UiAreaHandler();

	handler->draw = new nbind::cbFunction(drawCb);
	handler->mouseEvent = new nbind::cbFunction(mouseEventCb);
	handler->mouseCrossed = new nbind::cbFunction(mouseCrossedCb);
	handler->dragBroken = new nbind::cbFunction(dragBrokenCb);
	handler->keyEvent = new nbind::cbFunction(keyEventCb);

	handler->Draw = Draw;
	handler->MouseEvent = MouseEvent;
	handler->MouseCrossed = MouseCrossed;
	handler->DragBroken = DragBroken;
	handler->KeyEvent = KeyEvent;

	return handler;
}
```

So, I get a struct shaped like `libui` wants, and every time it call one of the functions in the struct, I call the corresponding js callback.

The APIs are not completed yet, but the method seems to work well...

1) Do you see a way to simplify this stuff?
2) Do you think this kind of use case could be automated by `nbind` in a future release?

**Comment by parro-it** [comment]
Oh if you want to give a look, the partial implementation is [here](https://github.com/parro-it/libui-node/tree/ui-area/src/UiArea)

**Comment by jjrv** [comment]
That's a very clever way to solve the problem, but are you sure it's meant to be used that way? It sounds a bit dangerous to add new fields to the struct, in case libui then makes a copy of it for some reason without knowing about the added fields. Does libui guarantee it's OK to extend it like that? Currently it does seem like libui assumes (requires even) that you keep ownership of the `uiAreaHandler` contents so it seems fine, but I can't find anything in the docs...

I can't think of what nbind could do to make this cleaner while also useful with other libraries.

**Comment by parro-it** [comment]
> I can't think of what nbind could do to make this cleaner while also useful with other libraries.

A similar pattern could be used every time a native lib require you to pass an object with methods you have to implement in javascript. I can't think of an example at the moment, but I'm sure there are many...

 > Currently it does seem like libui assumes (requires even) that you keep ownership of the uiAreaHandler

Uhm I didn't thought about this problem. I think it did, but I will ask @andlabs for a confirmation..

Thank you for the advice...

**Comment by andlabs** [comment]
Yes, you keep ownership of the uiAreaHandler. libui only cares about the address you give uiNewArea(); it doesn't copy anything. You can even use the same uiAreaHandler on multiple uiAreas, which is why you get the uiArea as a parameter in each function.

In fact, this is the intent of the design: you make the first field of your handler struct a `uiAreaHandler` and stick extra fields at the end, like in COM or C++. Some people have asked for the more conventional `void *data` extra parameter, but...

**Comment by parro-it** [comment]
Fine @andlabs, thank you!

**Comment by jjrv** [comment]
I think most libraries use the `void *data` approach and take ownership of the function pointers, so that would require a different approach to automatize through nbind. The current libui binding code looks pretty clean so I'll consider extra support if more similar cases come up, but the current situation seems acceptable.
