### ISSUE TITLE
Support for events?

### ISSUE THREAD

**Issue by simopaasisalo** [charto/nbind#23]
Hi,

Is there a way for JS to subscribe to a C++ event? For example [this MSDN snippet:](https://msdn.microsoft.com/en-us/library/4b612y2s.aspx)
```
// mcppv2_events.cpp
// compile with: /clr
using namespace System;

// declare delegates
delegate void ClickEventHandler(int, double);
delegate void DblClickEventHandler(String^);

// class that defines events
ref class EventSource {
public:
   event ClickEventHandler^ OnClick;   // declare the event OnClick
   event DblClickEventHandler^ OnDblClick;   // declare OnDblClick

   void FireEvents() {
      // raises events
      OnClick(7, 3.14159);
      OnDblClick("Hello");
   }
};

// class that defines methods that will called when event occurs
ref class EventReceiver {
public:
   void OnMyClick(int i, double d) {
      Console::WriteLine("OnClick: {0}, {1}", i, d);
   }

   void OnMyDblClick(String^ str) {
      Console::WriteLine("OnDblClick: {0}", str);
   }
};

int main() {
   EventSource ^ MyEventSource = gcnew EventSource();
   EventReceiver^ MyEventReceiver = gcnew EventReceiver();

   // hook handler to event
   MyEventSource->OnClick += gcnew ClickEventHandler(MyEventReceiver, &EventReceiver::OnMyClick);
   MyEventSource->OnDblClick += gcnew DblClickEventHandler(MyEventReceiver, &EventReceiver::OnMyDblClick);

   // invoke events
   MyEventSource->FireEvents();

   // unhook handler to event
   MyEventSource->OnClick -= gcnew ClickEventHandler(MyEventReceiver, &EventReceiver::OnMyClick);
   MyEventSource->OnDblClick -= gcnew DblClickEventHandler(MyEventReceiver, &EventReceiver::OnMyDblClick);
}
```
How would I use nbind to get `OnClick`-events to register on the JS side?

**Comment by jjrv** [comment]
[libui-node](https://github.com/parro-it/libui-node) binds a C GUI library to JavaScript using nbind and has several examples of listening to events. Basically you need a C++ function that takes a JavaScript callback, which it then copies and stores for calling when an event happens.

See for example `onClosing` in [`UiWindow`](https://github.com/parro-it/libui-node/blob/8c4b4d9c9354bf740a1d5745dbae95204e1ff6e0/src/UiWindow.cc). The `UiWindow::onClosing` method is exported to JavaScript and takes a callback, copies it and tells libui to call `UiWindow_onClosing` with the JavaScript callback as custom data. It then casts the data pointer back to a callback handle and calls it.

**Comment by simopaasisalo** [comment]
Oh yeah, I tried to get what the libui was doing earlier, but your explanation really explained it well. My working test code is below - any gotchas?
```
class EventTest{
private:
  nbind::cbFunction * SensorEventCallback;

public:

  void onSensorEvent(nbind::cbFunction & cb) {
    SensorEventCallback = new nbind::cbFunction(cb);
  	CANAdapter_SensorEvent(
      0,
  		SensorEventCallback
  	);
  }

  static void CANAdapter_SensorEvent(int n,void *data)
  {
  	nbind::cbFunction *cb = (nbind::cbFunction *) data;
    printf("SensorEventC++:%d\n", n);
  	(*cb)(n);
  }

  void open(){
    printf("Opening\n");
    fakeEvents(4);
    printf("Opened\n");
  }

  void close(){
    printf("Closed\n");
  }

  void fakeEvents(int n){
    for (int i=n; i>0; i--) {
      CANAdapter_SensorEvent(i, SensorEventCallback);
      std::this_thread::sleep_for (std::chrono::seconds(1));
    }
  }
};
```

**Comment by parro-it** [comment]
Regarding your comment:

> //could I not just as well drop the parameter and just call SensorEventCallback here?

No, you can't because your static method has no access to `this`. You have to pass either the callback as you are doing, or the current instance in `data` argument.
