### ISSUE TITLE
Allow null as value for any pointer argument

### ISSUE THREAD

**Issue by parro-it** [charto/nbind#24]
Actually, when defining a function argument as a pointer to a class, it's impossibile to pass `null` as value.
If you pass `null`, you got `TypeError: Type mismatch` exception.

**Comment by jjrv** [comment]
You mean passing JavaScript `null` should become C++ `nullptr` when passed to a function expecting a `MyClass *` argument? Not sure if that's a good idea in the general case... At the moment I think you can do:

```C++
MyClass *getNull() { return(nullptr); }
```

This gives you a "typed" null pointer you can pass to other functions. Would that be enough?

**Comment by parro-it** [comment]
> You mean JavaScript null should become C++ nullptr when passed to a function expecting a MyClass * argument?

Exactly...

> Not sure if that's a good idea in the general case...

Why not? Seems natural that js `null` become NULL on native side...

> This gives you a "typed" null pointer you can pass to other functions. Would that be enough?

The workaround is perfect, I will try it... but I still think it could be better to just use null in future releases of nbind. Do you think is difficult to implement?

**Comment by jjrv** [comment]
It's not difficult to implement, but then you can no longer rely on always receiving a valid pointer and have to check all pointer parameters for `nullptr`.

A nice and harder to implement solution would be to annotate parameters accepting `nullptr` inside the `NBIND_CLASS` block. I'll check if there's a simple way to do so.

**Comment by parro-it** [comment]
Yes, an explicit annotation could be the ideal solution, I only have to accept nulls on some functions, in all other ones I'm fine with the error I'm getting now.

**Comment by jjrv** [comment]
I think this is now done in the v0.3 branch. Trying to release it during next week.

**Comment by parro-it** [comment]
This is working well too. Great work!
