### ISSUE TITLE
Save persistent instances of class pointers.

### ISSUE THREAD

**Issue by parro-it** [charto/nbind#26]
I need to save persistent instances of class pointers to avoid them being garbage collected if they are no more referenced by javascript.

I made some attempt using Persistent handles, but I was unsuccessful. 
There is an easy way to do this, similar to what we can do with callbacks?

**Comment by jjrv** [comment]
Currently there's no easy way. Which approach would you prefer?

- You can register a callback called when the instance is garbage collected, so you can make sure it won't get referenced afterwards.
- You make a reference to the instance persistent somehow, and then have to make it weak again when you no longer need it.

**Comment by parro-it** [comment]
> You make a reference to the instance persistent somehow, and then have to make it weak again when you no longer need it.

Definitely this, I need an instance to be valid because I have to pass it as argument in a callback later, 
so I can avoid to ask the user himself to keep care of persisting it (by saving the object somewhere on javascript side)

**Comment by parro-it** [comment]
The first option could be useful too, but I have no need to use it at the moment...

**Comment by jjrv** [comment]
By a lucky coincidence there's already a way to to this. but it's not exposed in the public API. I'll figure out how to add it.

Basically persisting a pointer would be:

```C++
Nan::Persistent<v8::Object> *ref = BindWrapper<Type>::getInstanceTbl()[ptr];
```

Not that `getInstanceTbl` is private.

Making it weak again:

```C++
ref->SetWeak(ref, weakCallback, Nan::WeakCallbackType::kParameter);
ref->MarkIndependent();
```

On Emscripten C++ objects instantiated with Javascript's `new` never get garbage collected anyway and need to be explicitly freed.

**Comment by jjrv** [comment]
On second thought, we should just use `std::shared_ptr` to ensure the object gets freed only after no references are left. This is now supported, so test replacing `Type *` with `std::shared_ptr<Type>` in your C++ function parameters, and then you should be able to persist the instance by keeping the pointer around.

**Comment by jjrv** [comment]
Check out v0.3.0 with initial `std::shared_ptr` support. I'll release v0.3.1 soon if you need changes.

**Comment by jjrv** [comment]
Closing this, you can comment if there's any problems with the current approach. I'll improve the smart pointer support soon.

**Comment by parro-it** [comment]
I'm a bit late, but I confirm you it's working  on 0.3
