### ISSUE TITLE
NBIND_ERR doesn't copy the character array

### ISSUE THREAD

**Issue by TanninOne** [charto/nbind#27]
Great library, seems to be very useful!

I noticed the hard way that NBIND_ERR neither copies nor releases the string passed in, so it relies on the caller to somehow manage the lifetime of the buffer until it is no longer required by nbind. This seems fairly impractical, so the functionality is only really usable with literals.
It may be sufficient to mention this in the documentation or simply replace Status::message by a std::string?

Also, would it be possible to provide something like NBIND_LOG as an easy way to log messages during development?

**Comment by jjrv** [comment]
Thanks for reporting this, I had only considered using it with string literals. I'll fix this then.

**Comment by TanninOne** [comment]
Thanks! It's really not a biggie, just something I stumbled over and thought it may be a trap others might step into.
