### ISSUE TITLE
Transferring a buffer

### ISSUE THREAD

**Issue by TanninOne** [charto/nbind#28]
I have the following requirement: On the c++ side I create a buffer with a 32-bit rgba image data (not encoded).
On the js side I want to feed this data into a Uint8ClampedArray to be used in a canvas element.
currently I return the buffer from c++ as a std::vector<uint8_t>. On the javascript side I get a number[] which I then have to convert to the correct type.
These conversions are quite expensive so I was wondering if there was a way to fill a the Uint8ClampedArray  directly on the c++ side? Or is this something that will be possible in the future?

This issue isn't really time critical for me, just want to know if I need to take a different approach.

**Comment by jjrv** [comment]
I guess you're targeting Emscripten and not Node.js? Currently there's no support for handling buffers on Node.js but it should be possible to directly share any block of memory between the languages and this will be supported later. On Emscripten the bindings are already based on JavaScript reading straight from the C++ heap, but it's not of type `Uint8ClampedArray` and C++ cannot access any other JavaScript objects or typed arrays besides its own heap.

On Emscripten I'd suggest passing the buffer's address from C++ to JavaScript by casting it to `uintptr_t` and directly accessing `binding.lib.HEAPU8`. At least Chrome has functions for copying data between typed arrays:

```JavaScript
canvas = document.createElement('canvas');
canvas.setAttribute('width', 800);
canvas.setAttribute('height', 600);
document.body.appendChild(canvas);

context = canvas.getContext('2d');
image = context.getImageData(0, 0, 800, 600);

data = image.data;

ptr = 0; // Receive this from C++ as uintptr_t
len = 800 * 600 * 4;

data.set(binding.lib.HEAPU8.subarray(ptr, ptr + len));
context.putImageData(image, 0, 0);
```

**Comment by TanninOne** [comment]
Sorry I didn't mention this, I didn't realize it made a difference: I'm targeting node.js - electron to be more specific.

**Comment by jjrv** [comment]
In that case your current approach is the best that's available now, but I'll improve it soon. If you want to help, you can put a minimal test case of your current approach on Github, so I can develop the new buffer support around it.

**Comment by TanninOne** [comment]
Thanks for looking into this. I've attached a zip with a testcase that should be representative for what I'm currently doing. It certainly may not be optimal, I'm fairly new to node.js.
Should be runnable:
npm install;  ./node_modules/.bin/electron .

[nbind_testcase.zip](https://github.com/charto/nbind/files/421969/nbind_testcase.zip)

**Comment by jjrv** [comment]
The testcase works, thanks! I'll see how to improve nbind to optimise it then.

**Comment by jjrv** [comment]
Just to let you know, I got it working... The API will look like this:

`img.cc`:

```C++
#include <vector>

#include "nbind/nbind.h"

void demo(nbind::Buffer buf) {
    uint8_t *data = buf.data();

    static const size_t width = 256;
    static const size_t height = 256;

    for(size_t row = 0; row < height; ++row) {
        for(size_t col = 0; col < width; ++col) {
            *data++ = row;
            *data++ = col;
            *data++ = 0;
            *data++ = 255;
        }
    }
}

NBIND_GLOBAL() {
    function(demo);
}
```

Script in `index.html`:

```JavaScript
    require('nbind').init(function(err, binding) {
        var lib = binding.lib;

        var canvas = document.getElementById('some-canvas');
        var gc = canvas.getContext('2d');
        var image = gc.getImageData(0, 0, 256, 256);

        lib.demo(image.data);

        gc.putImageData(image, 0, 0);
    });
```

The remaining issue is that my `Buffer` doesn't yet properly refer to the JavaScript typed array object, so the memory may suddenly get freed elsewhere and you have no way to find out. I'm not yet sure what to do about that though, since it seems the underlying `ArrayBuffer` is "externalized", managed by Electron and not V8.

In any case, for normal Node.js use I'll need to handle the garbage collection issue, and for Electron use an additional check if the "externalized" `ArrayBuffer` has been "neutered" is hopefully enough. You'll then need to call `buf.data()` every time you want to paint something, and it may return `nullptr` if the referenced memory has been freed on the JavaScript side.

**Comment by jjrv** [comment]
This is now implemented in master. Check out the tests, [C++](https://github.com/charto/nbind/blob/b5fbd3ba90208bb23cfb0c62a1dac2662fdc96df/test/Buffer.cc) and [JavaScript](https://github.com/charto/nbind/blob/b5fbd3ba90208bb23cfb0c62a1dac2662fdc96df/test/test.js#L311-L344) for usage examples.

Still need to update the documentation and fix a memory leak in old Node.js versions (0.10 and 0.12).

**Comment by TanninOne** [comment]
This works beautifully for my use case. I'll leave the issue open in case you want to track further progress here but from my side this change fulfils my requirement. Thanks again for your dedication!

**Comment by jjrv** [comment]
Great! The memory leak is now fixed and docs will be merged to master soon. Then I'll release version 0.3.1.
