### ISSUE TITLE
How to use nbind with header *.hpp and source *.cpp files?

### ISSUE THREAD

**Issue by subwaystation** [charto/nbind#33]
Hi everyone,

I am wondering how to use nbind having a C++ code structured in header files (ending with .hpp) and source files (ending with .cpp).
One major question is, how to let node-gyp know, when or how to use my header file?

My second question is where to put the nbind stuff:
The class declaration is in my hpp file:

#include <string>
#include <iostream>

class Greeter {
public:
  static void sayHello(std::string name);
};

The implementation in my cpp file:

#include "hello.hpp"

static void sayHello(std::string name) {
  std::cout<< "Hello, "<< name << "!\n";
}

#include "nbind/nbind.h"

NBIND_CLASS(Greeter) {
  method(sayHello);
}

Does it make sense to bind a class here? Or how to I bind a class which was declared in the header file....

All the best.

**Comment by jjrv** [comment]
Your implementation is correct, the `NBIND_CLASS` block belongs in the `.cpp` file. If placed in `.hpp`, it will create problems when several `.cpp` files include the same `.hpp`. For `node-gyp` to find all the files, you need to list the `.cpp` files in `binding.gyp`. For example:

```json
{
    "targets": [
        {
            "includes": [
                "auto.gypi"
            ],
            "sources": [
                "hello.cpp",
                "another.cpp"
            ]
        }
    ],
    "includes": [
        "auto-top.gypi"
    ]
}
```

**Comment by subwaystation** [comment]
Well, but it does not work for me..... please take a look into the attached files. Workflow describes the command line steps I am going through (and what they output). Maybe I am missing something here...









[Archive.zip](https://github.com/charto/nbind/files/578278/Archive.zip)

**Comment by jjrv** [comment]
Your `sayHello` is actually a function and not a member of the `Greeter` class. There's two possible changes to make this work.

You can turn `sayHello` into a class method:

```c++
void Greeter :: sayHello(std::string name) {
  std::cout<< "Hello, "<< name << "!\n";
}
```

Alternatively, if you don't want `sayHello` to be a class method then you can change the ending of `hello.cpp` to:

```c++
NBIND_GLOBAL() {
  function(sayHello);
}
```

Then in `hello.js` you can do:

```JavaScript
lib.sayHello('you');
```

**Comment by subwaystation** [comment]
That did the trick! Thank you very much man :)
