### ISSUE TITLE
How to handle deconstructors?

### ISSUE THREAD

**Issue by subwaystation** [charto/nbind#34]
Hi,

how do I handle deconstructors?
e.g.

#include <string>
#include <iostream>
 
struct Greeter {
  static void sayHello(std::string name) {
    std::cout<< "Hello, " << name << "!\n";
  }
  ~Greeter(void) {};
};

All the best.

**Comment by jjrv** [comment]
Are you targeting a native Node.js addon or Emscripten? In Node.js addons the destructor gets called automatically from the JavaScript garbage collector. In Emscripten you can call the object's `free()` method from JavaScript or enable the light garbage collector to do so automatically on the next tick.

**Comment by subwaystation** [comment]
I am targeting a native Node.js addon. 

Just to clarify for me:
JavaScript code:

var greeter = new Greeter();
var greeter = undefined;

This destroys the greeter object 'automatically' by the JavaScript garbage collector (as soon as ';' after undefined is passed or later)?  I do not have to care about the destructor in the C++ code and I do not care about binding it with nbind?

**Comment by jjrv** [comment]
The greeter object probably gets destroyed at some point afterwards. Node.js makes no guarantees, but in practice it seems destructors get called at least when the process exits. If you run the code with `node --expose-gc`, calling `gc()` from JavaScript should immediately call destructors of unreachable objects.

**Comment by jjrv** [comment]
Another thing: Node.js doesn't know the size of your C++ object, and doesn't care about remaining space in the C++ heap. So if your C++ object is holding onto a lot of memory, you might want to call its `.free()` method on the JavaScript side, which will then call the C++ destructor. That keeps only a tiny JavaScript wrapper object around, which Node.js manages and knows the size of.

**Comment by subwaystation** [comment]
Thanks for the detailed explanations. 👍
