### ISSUE TITLE
CheckWire::check in Caller.h conflict with macOS macro defined in AssertMacros.h

### ISSUE THREAD

**Issue by parro-it** [charto/nbind#40]
This give me following error when compiling:

```
Expected member name or ';' after declaration specifiers.
```

Followed by mahy other errors (someway related to the same cause)

I found this answer on SO:
 
http://stackoverflow.com/questions/31665095/xcode-error-compiling-c-expected-member-name-or-after-declaration-specifie

I'm effectively able to successfully compile by inserting `#undef check` at the beginning of `Caller.h`, but I'm not sure this is free of consequences, if you use the macro in some other file...

**Comment by jjrv** [comment]
Wow, naming a macro just `check` is pretty nasty. `nbind` is guilty of the same with macros like `function` and `method` but they're not meant to be in scope in the entire source file...

I'll rename `check` then, since it's only used internally...

**Comment by parro-it** [comment]
> Wow, naming a macro just check is pretty nasty. 

Really nasty, Indeed 😒

> I'll rename check then, since it's only used internally

Great!

**Comment by jjrv** [comment]
Does the current `develop` branch fix the issue?

**Comment by parro-it** [comment]
Yes, it does! Thank you for your help.
