### ISSUE TITLE
Enumerable properties

### ISSUE THREAD

**Issue by arcanis** [charto/nbind#41]
It seems that getters aren't currently enumerable, is it the expected behaviour? Is there a way to make them enumerable? I've tried the following, but got a Type Mismatch error:

```js
Object.defineProperty(lib.Point.prototype, 'row', {
    enumerable: true
});

Object.defineProperty(lib.Point.prototype, 'column', {
    enumerable: true
});
```

**Comment by jjrv** [comment]
I guess you're targeting Node.js? Which version are you using? I tried this in the nbind testbench:

```JavaScript
console.log(Object.keys(testModule.GetterSetter.prototype));
for(var i in testModule.GetterSetter.prototype) {
    console.log(i);
}
```

Both printed the getter names at least on Node 7.0. How is the code, that actually fails to enumerate the getters?

It seems using `defineProperty` on prototypes of functions defined in C++ is disallowed by Node.js, so the enumerability would need fixing inside nbind.

**Comment by arcanis** [comment]
Hm, actually I think I made a wrong diagnostic. In the test file I have something like a `deepEqual`, but it seems to only check for ownKeys (which makes sense, kinda). So the test was failing not because the properties weren't enumerable, but rather because they were set on the prototype rather than the actual objects.

Interestingly, the same behaviour can be seen by doing a simple `console.log` of a binded object. The property values are not displayed (ie. `Point {}` instead of `Point { row = 0, column = 0 }`).

**Comment by jjrv** [comment]
The properties won't show up in the keys of a class instance because they're not technically there... The getter and setter will access a value stored elsewhere. This is quite possible also in an ordinary class defined in plain JavaScript.

**Comment by jjrv** [comment]
Interestingly enough, you can set the key on the instance using `Object.defineProperty`. However, accessing it afterwards will no longer call the getter or setter. Not sure about this but it may be impossible to have a getter on the prototype and a matching enumerable key on the instance, with the getter still working.

**Comment by arcanis** [comment]
Yep, the getter would have to be created at the instance level, from inside the constructor (perhaps I could get away by creating a js class that would inherit from the Point class, and would define its own getters .. does nbind classes support being inherited by js classes?)

**Comment by jjrv** [comment]
It should work. However, if you try overriding methods using JavaScript, the C++ code will still only call methods defined in C++.

**Comment by jjrv** [comment]
I tried to copy the getter and setter from the prototype to the instance:

```JavaScript
function Blah() {
    var descY = Object.getOwnPropertyDescriptor(this.constructor.prototype, 'y');

    Object.defineProperty(this, 'y', {
        enumerable: true,
        getter: descY.get,
        setter: descY.set
    });
}
```

...but I ran into `Error: Type mismatch at Function.getOwnPropertyDescriptor`.

In fact, I can't even call `console.log` on the prototype. V8 seems to lock down the properties of native code pretty hard, probably for browser security reasons.

**Comment by jjrv** [comment]
It seems you'd have to export the getter and setter as separate, ordinary methods with other names and then call `defineProperty` in your inherited class constructor, to turn them into an actual getter / setter pair.

**Comment by arcanis** [comment]
> It seems you'd have to export the getter and setter as separate, ordinary methods with other names and then call defineProperty in your inherited class constructor, to turn them into an actual getter / setter pair bound to the instance.

Yeah, I've thought about this, but unfortunately it isn't quite practical: my C++ would return unwrapped instance of the original class, in which the properties wouldn't have been set :/

> Would you rather read/write JavaScript object properties from C++ (since C++ class members cannot be made enumerable in JavaScript without ugly hacks)?

Is it possible ? I thought that complex objects weren't yet supported by nbind (I unfortunately can't use the v8 API directly, since the asm.js is the main feature I'm going to use here).

**Comment by jjrv** [comment]
This is again hackish, somewhat undocumented and untested... Your JavaScript class constructor could call a parent C++ class method, passing it `this` and one or more arbitrary JavaScript functions. The C++ code can then store those references and call the function(s) passing the object and other stuff as arguments. That JavaScript function can then change and retrieve information from the JavaScript object.

The C++ type needed to receive an arbitrary JavaScript function and call it with any argument and return types is `nbind::cbFunction` as documented in the readme. The C++ type for an arbitrary object, such as the `this` pointer, is `nbind::External` (undocumented). Internally, nbind uses it for callback handles on the Emscripten target and type reflection for TypeScript definition generation on the Node.js target.

This should work but may not be ideal in the long term. On Node.js, a much faster API for accesing JavaScript objects could be provided. However I think on the Emscripten target, the above is as fast as it gets, anyway. A future API may be cleaner, but probably not much faster.

**Comment by jjrv** [comment]
Returning new, properly wrapped instances is another interesting challenge. I think the C++ return type could be `nbind::External`, and it could first call a JavaScript function through `cbFunction::call<nbind::External>` passing it the object you were planning to return... The JavaScript function would then wrap and return it, and the initial C++ function would return that wrapped object.

If you're interested in something this hackish, I can do some testing to verify it will work and give you a working example (if possible).

Currently `nbind::External` is like a black box, and any future API for accessing JavaScript objects from C++ would basically be manipulating `nbind::External` instances.

**Comment by arcanis** [comment]
Hm, I see. I will have to see with the maintainers of the project I'm trying to build with asm.js, since doing this could very well be a bit too hackish, but thanks anyway.

I think this issue can be closed. Worst case scenario, if someone *really* needs to make its properties visible from the outside as ownKeys, they should be able to find on this issue some leads to get them going.
