### ISSUE TITLE
function macro conflict

### ISSUE THREAD

**Issue by TanninOne** [charto/nbind#44]
There is a type std::function in the standard header <functional> your "function" macro conflicts with.
This is quite ugly, basically I have to #undef function and redefine it with a different name after including the nbind header.

There are a few other macro names that I find too generic, especially "args", "inherit", "method", "field", "getter".
I do realize these are convenient but there is a high risk of conflicting with other libs. "function" conflicting with a standard library is extra-bad imho.

**Comment by jjrv** [comment]
You should `#include "nbind/api.h"` at the top of your file if needed. Everything it defines is in the `nbind` namespace.

Then at the *bottom* of some of your source files add stuff like:

```C++
#include "nbind/nbind.h"

#ifdef NBIND_GLOBAL

NBIND_GLOBAL(...) {
    function(...);
}

#endif
```

The macros like `function` can now only conflict with other macros, or code inside the `NBIND_GLOBAL` block.

There's one case where this will soon cause problems... Once support for `std::function` type callbacks is added, if your constructor takes such a callback then `constructor<std::function<Type>>()` will conflict with the macro. I'll figure out a fix when that feature is ready.

Let me know if this usage pattern doesn't work for you or if you're still having naming conflicts.

**Comment by jjrv** [comment]
I can of course add a new header `nbind-noconflict.h` which defines macros named like `NBIND_FUNCTION`. You can then `#include` it anywhere, but the binding code block will look a bit ugly.

**Comment by TanninOne** [comment]
Ahh, sorry, I didn't notice you already mention this in the readme. I didn't have any conflicts on my first projects with including at the top so I always just continued from there.

Having an include statement in the middle of the code is also frequently considered bad style and may violate coding guidelines in some places.

Personally I would prefer all macros to be uppercased and with a prefix. If someone finds that ugly they can still "#define function NBIND_FUNCTION" above the NBIND_GLOBAL block.

But this is all just my opinion, as long as you provide a solution I can live with it.

**Comment by jjrv** [comment]
I'm thinking of adding a new header with the naming you prefer, and making the current header contain the sort of `#define`s you mentioned. This will be done in the next release.

Everything should look as pretty and approachable as possible to give a good first impression in the quick start tutorial and similar. I couldn't find a way to do that without breaking a few style rules... But you're right, it should be left as an option so you can later opt out of the non-conventional macros.

**Comment by jjrv** [comment]
This is now merged in master. Turned out rather more complicated than just a few `#define`s... Also note the alternative syntax the macros expand to. That's also a stable API now, except for `NBIND_GLOBAL` and `NBIND_FUNCTION` which will change later. With this latest update, the alternative syntax `NBIND_MULTIFUNCTION` was finished.
