### ISSUE TITLE
Support Emscripten

### ISSUE THREAD

**Issue by jjrv** [charto/nbind#5]
This issue is here to track progress of ongoing development. nbind should support compiling with Emscripten and running the exact same code on Node.js and recent web browsers.

- [x] Static methods.
- [x] Numeric argument and return types.
- [x] Pointers wrapped as objects.
- [x] Constructors.
- [x] Destructors.
- [x] Non-static methods.
- [x] String argument and return types.
- [x] Getters and setters.
- [x] Callbacks.
- [x] ...without leaking handles.
- [x] Value types.
- [ ] ...with MethodResultConverter.
- [x] ...without leaking handles.
- [x] Vectors.
- [x] Load Emscripten module through `require('nbind')`.
- [x] Integrate Emscripten to Autogypi build system.
- [x] Fix `cflags` in `nbind.gypi` to find `--js-library` inside `nbind`.
- [x] Test building on Windows.
- [x] Add to Travis.
- [ ] Add to AppVeyor.

**Comment by jjrv** [comment]
Now supporting classes with static methods, using only numbers as argument and return types.

**Comment by jjrv** [comment]
Using gyp with Emscripten on Windows seems complicated. A Visual Studio plugin might help: https://github.com/james-allison/vs-tool/tree/VS2013-Support

**Comment by bsergeev** [comment]
Yes, gyp on Windows is often troublesome, there are some workarounds posted (although I haven't tried them myself):
https://www.robertkehoe.com/2015/03/fix-node-gyp-rebuild-error-on-windows/

But what this Visual Studio plugin has to do with gyp? Will you be able to replace gyp project with Visual Studio (or, perhaps, CMake) project to build node extensions and/or invoke Emscripten?

BTW, you don't need a VS extension to invoke Emscripten, as it can be easily invoked from a command line/script as a custom build step in Visual Studio.

**Comment by jjrv** [comment]
`nbind` tests and examples are compiled with `node-gyp` since it's nicely integrated into the Node.js ecosystem. On Linux, it was possible to persuade it to compile with Emscripten by setting `CXX` in `make_global_settings` in `binding.gyp`. I didn't find any documentation of how to do the same in Visual Studio and suspected that it's not possible.

`node-gyp` can generate a `Makefile` on Windows but neither Microsoft's `nmake` nor GNU's `gnumake` was able to compile it, so it would be better to configure `node-gyp` to generate a suitable `.sln` or patch it afterwards to use `emcc`.

The goal is that `nbind` users could compile their project to a Node.js or Emscripten module by changing a single setting somewhere, in the same way on Windows, Linux and OS X.

**Comment by jjrv** [comment]
@bsergeev thanks for the hints, I got it working. Only problem is that it always re-compiles everything. I guess it will be up to the Visual Studio user to fix that manually somehow, but `nbind` is now able to create a basic Emscripten solution that compiles.

Now I'll have to fix a bug with callbacks when using the `-O2` option in Emscripten, improve documentation and then it's ready for release. Rest of the missing features will go to issue #8.

**Comment by jjrv** [comment]
Closing this now, the last missing things can be done later.
