### ISSUE TITLE
Weird behavior when naming a function 'readdir'

### ISSUE THREAD

**Issue by kenOfYugen** [charto/nbind#54]
I stumbled upon a weird thing. As I am writing a node.js `fs.readdir` replacement function, I named the exposed function `readdir` and I couldn't get it to build. Any other name worked fine.

I proceeded by cloning the [examples](https://github.com/charto/nbind-examples) and renamed the `sayHello` function to `readdir` in both `6-functions.js` and `6-functions.cc`.

The behavior was reproduced and it failed to build once again:
```
In file included from ../6-functions.cc:7:0:
../node_modules/nbind/include/nbind/nbind.h:30:112: error: no matching function for call to ‘nbind::FunctionDefiner::FunctionDefiner(const char [8], <unresolved overloaded function type>)’
 #define function(name, ...) nbind::FunctionDefiner NBIND_UNIQUE(definer, __LINE__)(#name, &name, ## __VA_ARGS__)
                                                                                                                ^
../6-functions.cc:10:3: note: in expansion of macro ‘function’
   function(readdir);
   ^~~~~~~~
In file included from ../node_modules/nbind/include/nbind/nbind.h:9:0,
                 from ../6-functions.cc:7:
../node_modules/nbind/include/nbind/FunctionDefiner.h:13:2: note: candidate: template<class ReturnType, class ... Args, class ... Policies> nbind::FunctionDefiner::FunctionDefiner(const char*, ReturnType (*)(Args ...), Policies ...)
  FunctionDefiner(
  ^~~~~~~~~~~~~~~
../node_modules/nbind/include/nbind/FunctionDefiner.h:13:2: note:   template argument deduction/substitution failed:
In file included from ../6-functions.cc:7:0:
../node_modules/nbind/include/nbind/nbind.h:30:112: note:   couldn't deduce template parameter ‘ReturnType’
 #define function(name, ...) nbind::FunctionDefiner NBIND_UNIQUE(definer, __LINE__)(#name, &name, ## __VA_ARGS__)
                                                                                                                ^
../6-functions.cc:10:3: note: in expansion of macro ‘function’
   function(readdir);
   ^~~~~~~~
In file included from ../node_modules/nbind/include/nbind/nbind.h:9:0,
                 from ../6-functions.cc:7:
../node_modules/nbind/include/nbind/FunctionDefiner.h:8:7: note: candidate: constexpr nbind::FunctionDefiner::FunctionDefiner(const nbind::FunctionDefiner&)
 class FunctionDefiner {
       ^~~~~~~~~~~~~~~
../node_modules/nbind/include/nbind/FunctionDefiner.h:8:7: note:   candidate expects 1 argument, 2 provided
../node_modules/nbind/include/nbind/FunctionDefiner.h:8:7: note: candidate: constexpr nbind::FunctionDefiner::FunctionDefiner(nbind::FunctionDefiner&&)
../node_modules/nbind/include/nbind/FunctionDefiner.h:8:7: note:   candidate expects 1 argument, 2 provided
```

Thinking there might be some weird interaction with the native modules of node.js, I tried out naming the function `readdirSync`. It built fine.

Next I tried `reabbir` and a random 7 lowercase character name, such as `qwertyu`, and again it built fine.

`nbind`'s codebase doesn't seem to mention `readdir` anywhere. 

I can reproduce this in both Linux and Mac. Steps:
1. `git clone https://github.com/charto/nbind-examples`
2.  Rename `sayHello` to `readdir` in both `6-functions.js` and `6-functions.cc`
3. `npm install`

---
Edit:
Ok, `stat` also fails, so I'm guessing there is some interference with node.js' builtins.

**Comment by jjrv** [comment]
The name is conflicting with the standard C library, so you end up defining a new overload for it. When `nbind` tries to autodetect argument and return types, the C++ compiler doesn't know which overload you want and fails to compile.

The easiest solution is to rename your C++ function to something else and only expose it to JavaScript as `readdir` using syntax like `function(myReaddir, "readdir");`

If for some reason you can't change the C++ function name, you can put it an a namespace or failing that, use the `multifunction` macro instead. The latter option will require manually specifying argument types to distinguish between overloads.

**Comment by kenOfYugen** [comment]
Ok then, I don't really have to call it `readdir`, wasn't sure whether it was a use case for `multifunction` or a possible bug, it seemed too weird to ignore it.
