### ISSUE TITLE
Support TypeScript

### ISSUE THREAD

**Issue by jjrv** [charto/nbind#6]
nbind should automatically generate TypeScript `.d.ts` definition files and Closure Compiler externs from the C++ code. This should be done with a simple interface to query internal typing data, and an external NPM package that can read such data and output bindings in either format. This should work regardless of whether the C++ code was compiled using Emscripten or natively to a Node.js plugin. This is scheduled after Emscripten support. The separate tasks are:

- [x] Read type information from Node.js module.
- [x] Same, but from Emscripten.
- [ ] Output TypeScript definitions.

**Comment by jjrv** [comment]
Closure compiler and comment extraction could be supported later:

- [ ] Extract doc comments from C++ headers.
- [ ] Support passing output through Closure Compiler.
- [ ] Output Closure Compiler externs.

**Comment by vehsakul** [comment]
Typescript definitions would be a killer feature :+1:

**Comment by jjrv** [comment]
This has finally landed in master. Run the newly included tool `ndts` after `node-gyp` (in the same directory) and it prints TypeScript definitions for the C++ module. The output can be directed to a `.d.ts` file and imported normally, see the `test` scripts in [`package.json`](https://github.com/charto/nbind/blob/05b526b0d177cc8599b9ccdd5e47f6da3c596844/package.json#L25-L26) and [`test/test.ts`](https://github.com/charto/nbind/blob/05b526b0d177cc8599b9ccdd5e47f6da3c596844/test/test.ts#L9-L14) for a working example:

```TypeScript
import * as foo from './testlib';

const binding = nbind.init<typeof foo>();
```

More documentation still to be written...
