### ISSUE TITLE
Nbind doesn't return the right types and segfault

### ISSUE THREAD

**Issue by arcanis** [charto/nbind#70]
You can check my `split-config` branch here: https://github.com/arcanis/yoga/tree/split-config

Compilation / testing is done via:

```
$> cd javascript/
$> npm install
$> npm run test:node
```

If you run the tests a few times, you'll quickly see them fail. After adding debug logs inside the object creators & destructors, it appears that in some particular cases, nbind is returning the wrong object types:

```
Creating config 0x2a005b0
Creating node 0x29bd490
Creating node 0x29c14b0
Deleting node 0x29c14b0
Deleting node 0x29bd490
Deleting config 0x2a005b0
  ✓ absolute_layout_width_height_start_top
Creating config 0x29bd490
Deleting node 0x29bd490
[2]    4169 segmentation fault (core dumped)  TEST_ENTRY=node /home/arcanis/.nvm/versions/node/v6.2.2/bin/node --expose-gc
```

As you can see, right before segfaulting, nbind calls the destructor for a node, even if the actual object was a config! I've double-checked, and I see no memory error before this point (valgrind doesn't report anything). Because this fail doesn't occur inside valgrind, and because it doesn't always happen, my guess is that there's some kind of race condition somewhere inside nbind, but I'm not familiar enough with the codebase to know where.

Unfortunately, this issue is quite critical for us, I'm not sure we'll be able to workaround this one :( Do you have any idea regarding what might cause this?

**edit** Something I noticed: when the tests pass, the same pointers are used for the same data type (we force garbage collection, so it makes sense). When they fail, it's after the config factory has returned a pointer that was previously a node. Could it be possible that nbind fails to update the type of the pointer when it is reallocated?

**Comment by arcanis** [comment]
My edit put me on the right track - it seems that I messed up how I was declaring `NBIND_DUPLICATE_POINTERS` (I initially put it has a `#define` macro before including `nbind/nbind.h`). Adding it as global switch (inside `bindings.gyp`) fixed the issue.

That being said, if we hadn't already been using `NBIND_DUPLICATE_POINTERS`, then we might have had an issue :/

**Comment by jjrv** [comment]
Is it possible that you sometimes included `nbind/nbind.h` with `NBIND_DUPLICATE_POINTERS` and sometimes without it? That might cause different object files to have an incompatible API between each other.

**Comment by arcanis** [comment]
Yep, that was exactly this. I instead should have defined the value using a CFLAG: https://github.com/facebook/yoga/pull/487/files#diff-ba4d9c95300c6cf94d95480c7dafc308R8

**Comment by jjrv** [comment]
I guess in the next version, `NBIND_DUPLICATE_POINTERS` should probably be the default (to match asm.js functionality) and a similar define could switch to the current behavior.
