### ISSUE TITLE
any posibility to bind C99 library to js?

### ISSUE THREAD

**Issue by hbakhtiyor** [charto/nbind#75]

**Comment by jjrv** [comment]
You need to write a C++ wrapper (see how [libui-node](https://github.com/parro-it/libui-node) works) or use [N-API](https://github.com/nodejs/abi-stable-node), not yet included in a stable Node.js release.

**Comment by hbakhtiyor** [comment]
thanks, does libui-mode use nbind with c++ wrapper?

**Comment by jjrv** [comment]
Yes, there's a library [libui](https://github.com/andlabs/libui) written in C, and libui-node is a C++ wrapper for it, using nbind to communicate with Node.js.

**Comment by jjrv** [comment]
Closing, feel free to re-open if you need more info.

**Comment by hbakhtiyor** [comment]
@jjrv do you know any resources/tutorials about these?

**Comment by jjrv** [comment]
You could try a Google search `c++ wrapper for c library`. For example see http://stackoverflow.com/questions/2690601/c-wrapper-for-c-library

You might want to create a simple C++ hello world style Node.js addon first, to familiarize yourself with nbind.

**Comment by parro-it** [comment]
You may also give a look at https://github.com/parro-it/screen-info
Much less code than `libui` to grasp, but still a complete example of c++ wrapper / nbind
