### ISSUE TITLE
No init() function

### ISSUE THREAD

**Issue by computerquip-streamlabs** [charto/nbind#80]
The docs use an init() function all over the place but I don't see it in the object passed from the module. Other than that, the module seems to work correctly. Are the docs incorrect?

**Comment by jjrv** [comment]
It should be there. In a Node.js prompt try `require('nbind')` and it should print:

```
> require('nbind')
{ Binding: [Function: Binding],
  find: [Function: find],
  init: [Function: init] }
```

`init` loads the actual module and returns an object with the exported C++ classes and functions.

**Comment by computerquip-streamlabs** [comment]
I was loading the module directly. It seems I can pass a relative folder name to init() to differentiate between multiple nbind bindings so I'll do that.
