### ISSUE TITLE
npm run -s -- ndts . > lib-types.d.ts doesn't seem to do anything

### ISSUE THREAD

**Issue by kayvanbree** [charto/nbind#99]
I'm working on Windows in WebStorm, I have an Angular 5 electron app up and running and I want to create a nodejs extension so I can use opencv in c++. 

When running the `npm run -s -- ndts . > lib-types.d.ts` ndts doesn't generate anything inside lib-types.d.ts. Therefor TypeScript doesn't recognize lib-types as a module. Compiling seems to work as I have a build folder with my obj file. 

When running the command it doesn't print anything to the console, so I can't figure out what's going wrong. Can you help me figure out what is wrong? I can provide more information, when I know what information to provide.

**Comment by jjrv** [comment]
Can you share your C++ code? Is there an `NBIND_CLASS` block? Does calling it from plain JavaScript work?

**Comment by kayvanbree** [comment]
Hey jjrv, all code I have can be temporarily found at https://bitbucket.org/kayvanbree/screencapture/overview. The c++ code was the following (based on the example): 

`#include <string>
#include <iostream>

struct Streaming {
  static void sayHello(std::string name) {
    std::cout
      << "Hello, "
      << name << "!\n";
  }
};

#include "nbind/nbind.h"

NBIND_CLASS(Streaming) {
  method(sayHello);
}`

When I add the following to index.html I get an error:

`<script>
      var nbind = require('nbind');
      var lib = nbind.init().lib;
      lib.Streaming.sayHello('something');

    </script>`

The error is:

`Uncaught Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at initNode (E:\Projects\streaming\frontend\node_modules\nbind\dist\nbind.js:141:15)
    at E:\Projects\streaming\frontend\node_modules\nbind\dist\nbind.js:115:13`

**Comment by kayvanbree** [comment]
I tried debugging the error I got:

 ![Debug window](https://i.imgur.com/e9qKTil.png)

I think this should contain the path information of my compiled module. Am I right about that?

**Comment by kayvanbree** [comment]
@jjrv I finally figured out that I forgot to include "ndts": "ndts" to my package.json. lib-types.d.ts is now actually generated with my class and method, like this: 

```javascript
import { Buffer } from "nbind/dist/shim";

export class NBindBase { free?(): void }

export class Streaming extends NBindBase {
	/** static void sayHello(std::string); */
	static sayHello(p0: string): void;
}
```

However, when I start my application (either on localhost or as Electron application) I get the following error: 

```
ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve '../../lib-types' in 'E:\Projects\streaming\frontend\src\app'
resolve '../../lib-types' in 'E:\Projects\streaming\frontend\src\app'
  using description file: E:\Projects\streaming\frontend\package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: E:\Projects\streaming\frontend\package.json (relative path: ./src/app)
    using description file: E:\Projects\streaming\frontend\package.json (relative path: ./lib-types)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        E:\Projects\streaming\frontend\lib-types doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        E:\Projects\streaming\frontend\lib-types.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        E:\Projects\streaming\frontend\lib-types.js doesn't exist
      as directory
        E:\Projects\streaming\frontend\lib-types doesn't exist
[E:\Projects\streaming\frontend\lib-types]
[E:\Projects\streaming\frontend\lib-types.ts]
[E:\Projects\streaming\frontend\lib-types.js]
[E:\Projects\streaming\frontend\lib-types]
 @ ./src/app/app.component.ts 14:18-44
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

I was wondering if you might be willing to publish an example how to use nbind with TypeScript. If I get this running I will publish a repository with an Angular Electron example.
